class=com.drskunk.sh3dikea.IkeaImportPlugin
name=IKEA Browser
description=Browse and import IKEA 3D models directly into your home
version=0.2.0
license=GPL v2 or later
provider=DrSkunk
applicationMinimumVersion=4.0
javaMinimumVersion=1.8
